"""Pest Control Directory — Flask app.

Server-rendered SEO directory over the scraped SQLite DB. Same playbook as
mobiledetailing.io: thousands of city/category/listing pages, sitemap, quote
form, AdSense slots. Unique long-form copy comes from the `content` table
(pre-generated by Gemini — see web/gen_content.py), never the live request.

Run:
    pip install flask
    python web/app.py            # http://127.0.0.1:5000
"""
import json
import os
import re
import sqlite3
import sys
from pathlib import Path

from flask import (Flask, abort, g, redirect, render_template, request,
                   url_for, Response)

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scraper"))
import db as dbmod  # noqa: E402  (schema + slugify live here)

app = Flask(__name__)
app.config["SITE_NAME"] = "Pest Control Directory"
# Canonical host for sitemap/canonicals/OG. Override with env DOMAIN when a
# custom domain is attached (no trailing slash).
app.config["DOMAIN"] = os.environ.get(
    "DOMAIN", "https://pestcontrol-directory-sigma.vercel.app")
app.config["ADSENSE_CLIENT"] = os.environ.get("ADSENSE_CLIENT", "")  # ca-pub-XXXX
app.config["GA_ID"] = os.environ.get("GA_ID", "")                    # G-XXXXXXXX
# Google Search Console verification token (the string in the meta-tag method).
app.config["GSC_VERIFICATION"] = os.environ.get("GSC_VERIFICATION", "")

CATEGORY_ICONS = {
    "General Pest Control": "fa-bug",
    "Exterminators": "fa-spray-can-sparkles",
    "Termite Control": "fa-house-crack",
    "Bed Bug Removal": "fa-bed",
    "Rodent Control": "fa-otter",
    "Mosquito Control": "fa-mosquito",
    "Wildlife Removal": "fa-crow",
}


# ---------------------------------------------------------------- db helpers
def get_db():
    if "db" not in g:
        # read-only + immutable: serverless filesystems are read-only, and this
        # avoids SQLite creating -wal/-journal lock files next to the bundled DB.
        uri = f"file:{dbmod.DB_PATH.as_posix()}?mode=ro&immutable=1"
        g.db = sqlite3.connect(uri, uri=True)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(_exc):
    d = g.pop("db", None)
    if d:
        d.close()


def slugify(s):
    return dbmod.slugify(s or "")


def content_for(key):
    """Fetch cached Gemini copy, or None. {intro, faq:[{q,a}]}."""
    row = get_db().execute(
        "SELECT intro, faq FROM content WHERE key = ?", (key,)
    ).fetchone()
    if not row:
        return None
    return {"intro": row["intro"],
            "faq": json.loads(row["faq"]) if row["faq"] else []}


# ---------------------------------------------------------------- context
@app.context_processor
def inject_globals():
    cats = [r["category"] for r in get_db().execute(
        "SELECT DISTINCT category FROM listings WHERE category IS NOT NULL "
        "ORDER BY category")]
    return {
        "SITE_NAME": app.config["SITE_NAME"],
        "ALL_CATEGORIES": cats,
        "CATEGORY_ICONS": CATEGORY_ICONS,
        "ADSENSE_CLIENT": app.config["ADSENSE_CLIENT"],
        "GA_ID": app.config["GA_ID"],
        "DOMAIN": app.config["DOMAIN"],
        "GSC_VERIFICATION": app.config["GSC_VERIFICATION"],
        "cat_slug": slugify,
    }


# ---------------------------------------------------------------- routes
@app.route("/")
def home():
    d = get_db()
    sort = request.args.get("sort", "reviews")
    order = {"reviews": "reviews DESC", "rating": "rating DESC, reviews DESC",
             "name": "name ASC"}.get(sort, "reviews DESC")
    listings = d.execute(
        f"SELECT * FROM listings ORDER BY {order} LIMIT 60").fetchall()
    cities = d.execute(
        "SELECT city, state, COUNT(*) n FROM listings "
        "GROUP BY city, state ORDER BY n DESC LIMIT 24").fetchall()
    cats = d.execute(
        "SELECT category, COUNT(*) n FROM listings "
        "WHERE category IS NOT NULL GROUP BY category ORDER BY n DESC").fetchall()
    total = dbmod.count(d)
    return render_template("index.html", listings=listings, cities=cities,
                           cats=cats, total=total, sort=sort)


@app.route("/listing/<slug>")
def listing(slug):
    row = get_db().execute(
        "SELECT * FROM listings WHERE slug = ?", (slug,)).fetchone()
    if not row:
        abort(404)
    nearby = get_db().execute(
        "SELECT * FROM listings WHERE city = ? AND state = ? AND slug != ? "
        "ORDER BY reviews DESC LIMIT 6",
        (row["city"], row["state"], slug)).fetchall()
    copy = content_for(f"listing:{slug}")
    return render_template("listing.html", l=row, nearby=nearby, copy=copy)


@app.route("/category/<slug>")
def category(slug):
    d = get_db()
    cats = {slugify(r["category"]): r["category"] for r in d.execute(
        "SELECT DISTINCT category FROM listings WHERE category IS NOT NULL")}
    name = cats.get(slug)
    if not name:
        abort(404)
    rows = d.execute(
        "SELECT * FROM listings WHERE category = ? ORDER BY reviews DESC "
        "LIMIT 200", (name,)).fetchall()
    copy = content_for(f"category:{slug}")
    return render_template("category.html", name=name, slug=slug,
                           rows=rows, copy=copy)


@app.route("/<state>/<cityslug>")
def city(state, cityslug):
    state = state.upper()
    d = get_db()
    # match by slug of city
    rows = d.execute(
        "SELECT * FROM listings WHERE state = ? ORDER BY reviews DESC",
        (state,)).fetchall()
    rows = [r for r in rows if slugify(r["city"]) == cityslug]
    if not rows:
        abort(404)
    cname = rows[0]["city"]
    copy = content_for(f"city:{cityslug}-{state.lower()}")
    return render_template("city.html", city=cname, state=state,
                           rows=rows[:200], copy=copy)


@app.route("/cities")
def cities():
    rows = get_db().execute(
        "SELECT city, state, COUNT(*) n FROM listings "
        "GROUP BY city, state ORDER BY state, city").fetchall()
    return render_template("cities.html", rows=rows)


@app.route("/categories")
def categories():
    rows = get_db().execute(
        "SELECT category, COUNT(*) n FROM listings WHERE category IS NOT NULL "
        "GROUP BY category ORDER BY n DESC").fetchall()
    return render_template("categories.html", rows=rows)


@app.route("/search")
def search():
    q = (request.args.get("q") or "").strip()
    cat = (request.args.get("category") or "").strip()
    loc = (request.args.get("city") or "").strip()
    sql = "SELECT * FROM listings WHERE 1=1"
    args = []
    if q:
        sql += " AND (name LIKE ? OR city LIKE ?)"
        args += [f"%{q}%", f"%{q}%"]
    if cat:
        sql += " AND category = ?"
        args.append(cat)
    if loc:
        sql += " AND (city LIKE ? OR state LIKE ?)"
        args += [f"%{loc}%", f"%{loc}%"]
    sql += " ORDER BY reviews DESC LIMIT 200"
    rows = get_db().execute(sql, args).fetchall()
    return render_template("search.html", rows=rows, q=q, cat=cat, loc=loc)


@app.route("/quote", methods=["POST"])
def quote():
    # Lead capture. Wire to email/CRM/DB later. For now, acknowledge.
    lead = {k: request.form.get(k) for k in
            ("name", "email", "phone", "city", "service", "details")}
    print("LEAD:", lead)  # TODO persist + notify
    return render_template("quote_thanks.html", lead=lead)


# ---------------------------------------------------------------- SEO
@app.route("/sitemap.xml")
def sitemap():
    from datetime import date
    d = get_db()
    base = app.config["DOMAIN"]
    today = date.today().isoformat()
    # (loc, priority, changefreq)
    urls = [(base + "/", "1.0", "daily"),
            (base + "/search", "0.5", "weekly"),
            (base + "/cities", "0.7", "weekly"),
            (base + "/categories", "0.7", "weekly")]
    for r in d.execute("SELECT DISTINCT category FROM listings "
                       "WHERE category IS NOT NULL"):
        urls.append((f"{base}/category/{slugify(r['category'])}", "0.8", "weekly"))
    for r in d.execute("SELECT DISTINCT city, state FROM listings"):
        urls.append((f"{base}/{r['state'].lower()}/{slugify(r['city'])}",
                     "0.7", "weekly"))
    for r in d.execute("SELECT slug FROM listings"):
        urls.append((f"{base}/listing/{r['slug']}", "0.6", "monthly"))
    xml = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, pri, cf in urls:
        xml.append(f"<url><loc>{loc}</loc><lastmod>{today}</lastmod>"
                   f"<changefreq>{cf}</changefreq><priority>{pri}</priority></url>")
    xml.append("</urlset>")
    return Response("\n".join(xml), mimetype="application/xml")


@app.route("/robots.txt")
def robots():
    txt = (f"User-agent: *\nAllow: /\n"
           f"Sitemap: {app.config['DOMAIN']}/sitemap.xml\n")
    return Response(txt, mimetype="text/plain")


@app.errorhandler(404)
def not_found(_e):
    return render_template("404.html"), 404


if __name__ == "__main__":
    app.run(debug=True, port=5000)
